name: CI

on:
  # Post-submit.
  push:
    branches: [main]

  # Pre-submit.
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [34]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Hardware Acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Install Flutter
        run: ./install-flutter.sh
      - name: Flutter Doctor
        run: flutter doctor
      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: "x86_64"
          target: google_apis
          script: |
            cd flutter
            SHARD=flutter_driver_android bin/dart dev/bots/test.dart
